'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WsUnilabsPatologia
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WsUnilabsPatologia.SoaServiceSoap")>  _
    Public Interface SoaServiceSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje PreAdmisionRegistroRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreAdmisionRegistro", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreAdmisionRegistro(ByVal request As WsUnilabsPatologia.PreAdmisionRegistroRequest) As WsUnilabsPatologia.PreAdmisionRegistroResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje PreAdmisionAnulacionRequest tiene encabezados.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/PreAdmisionAnulacion", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function PreAdmisionAnulacion(ByVal request As WsUnilabsPatologia.PreAdmisionAnulacionRequest) As WsUnilabsPatologia.PreAdmisionAnulacionResponse
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SecuredTockenwebservice
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private userNameField As String
        
        Private passwordField As String
        
        Private sucursalField As String
        
        Private anyAttrField() As System.Xml.XmlAttribute
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property UserName() As String
            Get
                Return Me.userNameField
            End Get
            Set
                Me.userNameField = value
                Me.RaisePropertyChanged("UserName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("Password")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Sucursal() As String
            Get
                Return Me.sucursalField
            End Get
            Set
                Me.sucursalField = value
                Me.RaisePropertyChanged("Sucursal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAnyAttributeAttribute()>  _
        Public Property AnyAttr() As System.Xml.XmlAttribute()
            Get
                Return Me.anyAttrField
            End Get
            Set
                Me.anyAttrField = value
                Me.RaisePropertyChanged("AnyAttr")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ADBE_PreAdmision
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fechaAdmisionField As System.Nullable(Of Date)
        
        Private historialPacienteField As String
        
        Private procedimientoField As String
        
        Private organoField As String
        
        Private pacienteAPPaternoField As String
        
        Private pacienteAPMaternoField As String
        
        Private pacienteNombresField As String
        
        Private pacienteTelefonoField As String
        
        Private sexoField As String
        
        Private especialidad_NombreField As String
        
        Private tipoDocumentoField As String
        
        Private documentoField As String
        
        Private pacienteMailField As String
        
        Private codigoProsotorField As String
        
        Private dxPresuntivoField As String
        
        Private cMPField As String
        
        Private medicoAPPaternoField As String
        
        Private medicoAPMaternoField As String
        
        Private unidadReplicacionField As String
        
        Private fechaLimiteAtencionField As System.Nullable(Of Date)
        
        Private codigoHCField As String
        
        Private numerocamaField As String
        
        Private servicioField As String
        
        Private tarifarioField As System.Nullable(Of Decimal)
        
        Private codigoOAField As String
        
        Private tipoOrdenField As String
        
        Private medicoNombresField As String
        
        Private idOrdenAtencionField As System.Nullable(Of Integer)
        
        Private cantidadSolicitadaField As System.Nullable(Of Integer)
        
        Private tipoAtencionField As System.Nullable(Of Integer)
        
        Private lineaField As System.Nullable(Of Integer)
        
        Private usuarioCreacionField As String
        
        Private fechaCreacionField As System.Nullable(Of Date)
        
        Private ipCreacionField As String
        
        Private componenteField As String
        
        Private fechaNacimientoField As System.Nullable(Of Date)
        
        Private componenteNombreField As String
        
        Private empleadora_NombreField As String
        
        Private empleadora_RUCField As String
        
        Private aseguradora_NombreField As String
        
        Private aseguradora_RUCField As String
        
        Private accesoField As String
        
        Private empresaProveedorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property FechaAdmision() As System.Nullable(Of Date)
            Get
                Return Me.fechaAdmisionField
            End Get
            Set
                Me.fechaAdmisionField = value
                Me.RaisePropertyChanged("FechaAdmision")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property HistorialPaciente() As String
            Get
                Return Me.historialPacienteField
            End Get
            Set
                Me.historialPacienteField = value
                Me.RaisePropertyChanged("HistorialPaciente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Procedimiento() As String
            Get
                Return Me.procedimientoField
            End Get
            Set
                Me.procedimientoField = value
                Me.RaisePropertyChanged("Procedimiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Organo() As String
            Get
                Return Me.organoField
            End Get
            Set
                Me.organoField = value
                Me.RaisePropertyChanged("Organo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property PacienteAPPaterno() As String
            Get
                Return Me.pacienteAPPaternoField
            End Get
            Set
                Me.pacienteAPPaternoField = value
                Me.RaisePropertyChanged("PacienteAPPaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property PacienteAPMaterno() As String
            Get
                Return Me.pacienteAPMaternoField
            End Get
            Set
                Me.pacienteAPMaternoField = value
                Me.RaisePropertyChanged("PacienteAPMaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property PacienteNombres() As String
            Get
                Return Me.pacienteNombresField
            End Get
            Set
                Me.pacienteNombresField = value
                Me.RaisePropertyChanged("PacienteNombres")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property PacienteTelefono() As String
            Get
                Return Me.pacienteTelefonoField
            End Get
            Set
                Me.pacienteTelefonoField = value
                Me.RaisePropertyChanged("PacienteTelefono")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property Sexo() As String
            Get
                Return Me.sexoField
            End Get
            Set
                Me.sexoField = value
                Me.RaisePropertyChanged("Sexo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=9)>  _
        Public Property Especialidad_Nombre() As String
            Get
                Return Me.especialidad_NombreField
            End Get
            Set
                Me.especialidad_NombreField = value
                Me.RaisePropertyChanged("Especialidad_Nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=10)>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
                Me.RaisePropertyChanged("TipoDocumento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=11)>  _
        Public Property Documento() As String
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
                Me.RaisePropertyChanged("Documento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=12)>  _
        Public Property PacienteMail() As String
            Get
                Return Me.pacienteMailField
            End Get
            Set
                Me.pacienteMailField = value
                Me.RaisePropertyChanged("PacienteMail")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=13)>  _
        Public Property CodigoProsotor() As String
            Get
                Return Me.codigoProsotorField
            End Get
            Set
                Me.codigoProsotorField = value
                Me.RaisePropertyChanged("CodigoProsotor")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=14)>  _
        Public Property DxPresuntivo() As String
            Get
                Return Me.dxPresuntivoField
            End Get
            Set
                Me.dxPresuntivoField = value
                Me.RaisePropertyChanged("DxPresuntivo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=15)>  _
        Public Property CMP() As String
            Get
                Return Me.cMPField
            End Get
            Set
                Me.cMPField = value
                Me.RaisePropertyChanged("CMP")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=16)>  _
        Public Property MedicoAPPaterno() As String
            Get
                Return Me.medicoAPPaternoField
            End Get
            Set
                Me.medicoAPPaternoField = value
                Me.RaisePropertyChanged("MedicoAPPaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=17)>  _
        Public Property MedicoAPMaterno() As String
            Get
                Return Me.medicoAPMaternoField
            End Get
            Set
                Me.medicoAPMaternoField = value
                Me.RaisePropertyChanged("MedicoAPMaterno")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=18)>  _
        Public Property UnidadReplicacion() As String
            Get
                Return Me.unidadReplicacionField
            End Get
            Set
                Me.unidadReplicacionField = value
                Me.RaisePropertyChanged("UnidadReplicacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=19)>  _
        Public Property FechaLimiteAtencion() As System.Nullable(Of Date)
            Get
                Return Me.fechaLimiteAtencionField
            End Get
            Set
                Me.fechaLimiteAtencionField = value
                Me.RaisePropertyChanged("FechaLimiteAtencion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=20)>  _
        Public Property CodigoHC() As String
            Get
                Return Me.codigoHCField
            End Get
            Set
                Me.codigoHCField = value
                Me.RaisePropertyChanged("CodigoHC")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=21)>  _
        Public Property Numerocama() As String
            Get
                Return Me.numerocamaField
            End Get
            Set
                Me.numerocamaField = value
                Me.RaisePropertyChanged("Numerocama")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=22)>  _
        Public Property Servicio() As String
            Get
                Return Me.servicioField
            End Get
            Set
                Me.servicioField = value
                Me.RaisePropertyChanged("Servicio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=23)>  _
        Public Property Tarifario() As System.Nullable(Of Decimal)
            Get
                Return Me.tarifarioField
            End Get
            Set
                Me.tarifarioField = value
                Me.RaisePropertyChanged("Tarifario")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=24)>  _
        Public Property CodigoOA() As String
            Get
                Return Me.codigoOAField
            End Get
            Set
                Me.codigoOAField = value
                Me.RaisePropertyChanged("CodigoOA")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=25)>  _
        Public Property TipoOrden() As String
            Get
                Return Me.tipoOrdenField
            End Get
            Set
                Me.tipoOrdenField = value
                Me.RaisePropertyChanged("TipoOrden")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=26)>  _
        Public Property MedicoNombres() As String
            Get
                Return Me.medicoNombresField
            End Get
            Set
                Me.medicoNombresField = value
                Me.RaisePropertyChanged("MedicoNombres")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=27)>  _
        Public Property IdOrdenAtencion() As System.Nullable(Of Integer)
            Get
                Return Me.idOrdenAtencionField
            End Get
            Set
                Me.idOrdenAtencionField = value
                Me.RaisePropertyChanged("IdOrdenAtencion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=28)>  _
        Public Property CantidadSolicitada() As System.Nullable(Of Integer)
            Get
                Return Me.cantidadSolicitadaField
            End Get
            Set
                Me.cantidadSolicitadaField = value
                Me.RaisePropertyChanged("CantidadSolicitada")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=29)>  _
        Public Property TipoAtencion() As System.Nullable(Of Integer)
            Get
                Return Me.tipoAtencionField
            End Get
            Set
                Me.tipoAtencionField = value
                Me.RaisePropertyChanged("TipoAtencion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=30)>  _
        Public Property Linea() As System.Nullable(Of Integer)
            Get
                Return Me.lineaField
            End Get
            Set
                Me.lineaField = value
                Me.RaisePropertyChanged("Linea")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=31)>  _
        Public Property UsuarioCreacion() As String
            Get
                Return Me.usuarioCreacionField
            End Get
            Set
                Me.usuarioCreacionField = value
                Me.RaisePropertyChanged("UsuarioCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=32)>  _
        Public Property FechaCreacion() As System.Nullable(Of Date)
            Get
                Return Me.fechaCreacionField
            End Get
            Set
                Me.fechaCreacionField = value
                Me.RaisePropertyChanged("FechaCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=33)>  _
        Public Property IpCreacion() As String
            Get
                Return Me.ipCreacionField
            End Get
            Set
                Me.ipCreacionField = value
                Me.RaisePropertyChanged("IpCreacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=34)>  _
        Public Property Componente() As String
            Get
                Return Me.componenteField
            End Get
            Set
                Me.componenteField = value
                Me.RaisePropertyChanged("Componente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=35)>  _
        Public Property FechaNacimiento() As System.Nullable(Of Date)
            Get
                Return Me.fechaNacimientoField
            End Get
            Set
                Me.fechaNacimientoField = value
                Me.RaisePropertyChanged("FechaNacimiento")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=36)>  _
        Public Property ComponenteNombre() As String
            Get
                Return Me.componenteNombreField
            End Get
            Set
                Me.componenteNombreField = value
                Me.RaisePropertyChanged("ComponenteNombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=37)>  _
        Public Property Empleadora_Nombre() As String
            Get
                Return Me.empleadora_NombreField
            End Get
            Set
                Me.empleadora_NombreField = value
                Me.RaisePropertyChanged("Empleadora_Nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=38)>  _
        Public Property Empleadora_RUC() As String
            Get
                Return Me.empleadora_RUCField
            End Get
            Set
                Me.empleadora_RUCField = value
                Me.RaisePropertyChanged("Empleadora_RUC")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=39)>  _
        Public Property Aseguradora_Nombre() As String
            Get
                Return Me.aseguradora_NombreField
            End Get
            Set
                Me.aseguradora_NombreField = value
                Me.RaisePropertyChanged("Aseguradora_Nombre")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=40)>  _
        Public Property Aseguradora_RUC() As String
            Get
                Return Me.aseguradora_RUCField
            End Get
            Set
                Me.aseguradora_RUCField = value
                Me.RaisePropertyChanged("Aseguradora_RUC")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=41)>  _
        Public Property Acceso() As String
            Get
                Return Me.accesoField
            End Get
            Set
                Me.accesoField = value
                Me.RaisePropertyChanged("Acceso")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=42)>  _
        Public Property EmpresaProveedor() As String
            Get
                Return Me.empresaProveedorField
            End Get
            Set
                Me.empresaProveedorField = value
                Me.RaisePropertyChanged("EmpresaProveedor")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PreAdmisionRegistro", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class PreAdmisionRegistroRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public SecuredTockenwebservice As WsUnilabsPatologia.SecuredTockenwebservice
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EmpresaProveedor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public Acceso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public Sucursal As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public PreAdmision As WsUnilabsPatologia.ADBE_PreAdmision
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SecuredTockenwebservice As WsUnilabsPatologia.SecuredTockenwebservice, ByVal EmpresaProveedor As String, ByVal Acceso As String, ByVal Sucursal As String, ByVal PreAdmision As WsUnilabsPatologia.ADBE_PreAdmision)
            MyBase.New
            Me.SecuredTockenwebservice = SecuredTockenwebservice
            Me.EmpresaProveedor = EmpresaProveedor
            Me.Acceso = Acceso
            Me.Sucursal = Sucursal
            Me.PreAdmision = PreAdmision
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PreAdmisionRegistroResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class PreAdmisionRegistroResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public PreAdmisionRegistroResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PreAdmisionRegistroResult As String)
            MyBase.New
            Me.PreAdmisionRegistroResult = PreAdmisionRegistroResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PreAdmisionAnulacion", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class PreAdmisionAnulacionRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://tempuri.org/")>  _
        Public SecuredTockenwebservice As WsUnilabsPatologia.SecuredTockenwebservice
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public EmpresaProveedor As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=1)>  _
        Public Acceso As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=2)>  _
        Public IdOrdenAtencion As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=3)>  _
        Public Linea As Integer
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=4)>  _
        Public Mensaje As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SecuredTockenwebservice As WsUnilabsPatologia.SecuredTockenwebservice, ByVal EmpresaProveedor As String, ByVal Acceso As String, ByVal IdOrdenAtencion As Integer, ByVal Linea As Integer, ByVal Mensaje As String)
            MyBase.New
            Me.SecuredTockenwebservice = SecuredTockenwebservice
            Me.EmpresaProveedor = EmpresaProveedor
            Me.Acceso = Acceso
            Me.IdOrdenAtencion = IdOrdenAtencion
            Me.Linea = Linea
            Me.Mensaje = Mensaje
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="PreAdmisionAnulacionResponse", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class PreAdmisionAnulacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public PreAdmisionAnulacionResult As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PreAdmisionAnulacionResult As Integer)
            MyBase.New
            Me.PreAdmisionAnulacionResult = PreAdmisionAnulacionResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface SoaServiceSoapChannel
        Inherits WsUnilabsPatologia.SoaServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SoaServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of WsUnilabsPatologia.SoaServiceSoap)
        Implements WsUnilabsPatologia.SoaServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsUnilabsPatologia_SoaServiceSoap_PreAdmisionRegistro(ByVal request As WsUnilabsPatologia.PreAdmisionRegistroRequest) As WsUnilabsPatologia.PreAdmisionRegistroResponse Implements WsUnilabsPatologia.SoaServiceSoap.PreAdmisionRegistro
            Return MyBase.Channel.PreAdmisionRegistro(request)
        End Function
        
        Public Function PreAdmisionRegistro(ByVal SecuredTockenwebservice As WsUnilabsPatologia.SecuredTockenwebservice, ByVal EmpresaProveedor As String, ByVal Acceso As String, ByVal Sucursal As String, ByVal PreAdmision As WsUnilabsPatologia.ADBE_PreAdmision) As String
            Dim inValue As WsUnilabsPatologia.PreAdmisionRegistroRequest = New WsUnilabsPatologia.PreAdmisionRegistroRequest()
            inValue.SecuredTockenwebservice = SecuredTockenwebservice
            inValue.EmpresaProveedor = EmpresaProveedor
            inValue.Acceso = Acceso
            inValue.Sucursal = Sucursal
            inValue.PreAdmision = PreAdmision
            Dim retVal As WsUnilabsPatologia.PreAdmisionRegistroResponse = CType(Me,WsUnilabsPatologia.SoaServiceSoap).PreAdmisionRegistro(inValue)
            Return retVal.PreAdmisionRegistroResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WsUnilabsPatologia_SoaServiceSoap_PreAdmisionAnulacion(ByVal request As WsUnilabsPatologia.PreAdmisionAnulacionRequest) As WsUnilabsPatologia.PreAdmisionAnulacionResponse Implements WsUnilabsPatologia.SoaServiceSoap.PreAdmisionAnulacion
            Return MyBase.Channel.PreAdmisionAnulacion(request)
        End Function
        
        Public Function PreAdmisionAnulacion(ByVal SecuredTockenwebservice As WsUnilabsPatologia.SecuredTockenwebservice, ByVal EmpresaProveedor As String, ByVal Acceso As String, ByVal IdOrdenAtencion As Integer, ByVal Linea As Integer, ByVal Mensaje As String) As Integer
            Dim inValue As WsUnilabsPatologia.PreAdmisionAnulacionRequest = New WsUnilabsPatologia.PreAdmisionAnulacionRequest()
            inValue.SecuredTockenwebservice = SecuredTockenwebservice
            inValue.EmpresaProveedor = EmpresaProveedor
            inValue.Acceso = Acceso
            inValue.IdOrdenAtencion = IdOrdenAtencion
            inValue.Linea = Linea
            inValue.Mensaje = Mensaje
            Dim retVal As WsUnilabsPatologia.PreAdmisionAnulacionResponse = CType(Me,WsUnilabsPatologia.SoaServiceSoap).PreAdmisionAnulacion(inValue)
            Return retVal.PreAdmisionAnulacionResult
        End Function
    End Class
End Namespace
